check if aegir is bootstrapping properly after upgrade or install
this will make sure things fail properly, see #1300216

diff --git a/debian/aegir-hostmaster.postinst b/debian/aegir-hostmaster.postinst
--- a/debian/aegir-hostmaster.postinst
+++ b/debian/aegir-hostmaster.postinst
@@ -99,6 +99,14 @@ case "$1" in
 EOF
         fi
         rm -f $TEMPFILE
+        # this will ensure that this script aborts if the site can't be bootstrapped
+        if su -s /bin/sh aegir -c 'drush @hostmaster status' 2>&1 | grep -q 'Drupal bootstrap.*Successful'; then
+            echo 'Aegir frontend bootstrap correctly, operation was a success!'
+        else
+            echo 'Aegir frontend failed to bootstrap, something went wrong!'
+            echo 'Look at the log above for clues or run with DPKG_DEBUG=developer'
+            exit 1
+        fi
     ;;
 
     abort-upgrade|abort-remove|abort-deconfigure)
